### ISSUE TITLE
Fix naming convention on vmx files

### ISSUE THREAD

**Issue by aebling** [JNPRAutomate/space-packer#6]
Determine wether or not to use the space- prefix on outgoing vmx files. They are different for ovf output as well as the fix copy of files. Packer is looking for files without the prefix.

**Comment by aebling** [comment]
To clarify. The ending output actually works in that none of the files in the vmx directory have the space- prefix attached. However it appears this is a bug in the image-prep.sh in that there are confusion on variable names since one is OVF_PREFIX and OVA_PREFIX. I am pretty sure this was not intentional but is very confusing. Needs cleanup. OVF and OVA seem intermixed.

**Comment by routelastresort** [comment]
Fair enough - all of these were quickly strung together with heavy multitasking going on.  Haste makes waste, yo.

**Comment by routelastresort** [comment]
Okay, this should be all fixed now (and newer images have `space-` on the front of everything).  This might be a VMware Fusion vs. Workstation, or Linux vs. Mac thing. I'll assume OSX, and Linux people can figure it out on their own.  I will periodically check, but most of this stems from ovftool - that's why the explicit directories are there.
